services:
  autosync:
    container_name: RepoPush
    build: .
    environment:
      ENV_FILE: /app/.env
    volumes:
      - ./.env:/app/.env:ro
      - /root/projects:/root/projects
    restart: unless-stopped

