services:
  autosync:
    container_name: RepoPush
    build: .
    environment:
      ENV_FILE: /app/.env
    volumes:
      - ./.env:/app/.env:ro
      - ${PROJECTS_PATH}:/projects
    restart: unless-stopped

